FROM golang:1.7-alpine

COPY . /go/src/github.com/StackPointCloud/docker-volume-profitbricks
WORKDIR /go/src/github.com/StackPointCloud/docker-volume-profitbricks

RUN set -ex \
    && apk add --no-cache --virtual .build-deps \
    gcc libc-dev \
    && go install --ldflags '-extldflags "-static"' \
    && apk del .build-deps

CMD ["/go/bin/docker-volume-profitbricks"]